#!/bin/sh

dig onet.pl mx +short | awk '{print $2}' | sort -u > /tmp/onet-correct-$$

for a in autograf.pl onet.com.pl onet.eu onet.pl opoczta.pl op.pl poczta.onet.pl spoko.pl vip.onet.pl vp.pl ; do
    dig $a mx +short | awk '{print $2}' | sort -u > /tmp/onet-maybe-$$
    [ -n $(cat /tmp/onet-correct-$$ /tmp/onet-maybe-$$ | sort | uniq -d) ] && echo $a
done > out/onet
